[incus]
src.git = "https://github.com/lxc/incus.git"
src.branch = "main"
fetch.git = "https://github.com/lxc/incus.git"

[river]
src.git = "https://codeberg.org/river/river.git"
src.branch = "master"
git.fetchSubmodules = true
fetch.git = "https://codeberg.org/river/river.git"
