on: [push]

env:
  ATTIC_KEY: ${{ secrets.ATTIC_KEY }}

jobs:
  flake-build:
    runs-on: stop/${{ matrix.system }}
    container:
      options: "--volume /nix:/host/nix"

    strategy:
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux

    steps:
      - uses: actions/checkout@v4

      - run: seed-ci --attic-use=true --nom=false --system ${{ matrix.system }}
