on:
  push:

jobs:
  flake-build:
    runs-on: local/${{ matrix.system }}

    strategy:
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux

    steps:
      - uses: actions/checkout@v4

      - run: |
          export HOME=$PWD
          nix develop .# --command seed-ci --attic-upload=true --attic-use=true --nom=false --sower-seed=true --system ${{ matrix.system }}
        env:
          ATTIC_KEY: ${{ secrets.ATTIC_KEY }}
          ATTIC_URL: ${{ vars.ATTIC_ENDPOINT }}
          ATTIC_CACHE: ${{ vars.ATTIC_CACHE }}
          SOWER_URL: ${{ vars.SOWER_URL }}
