on: [push]

env:
  ATTIC_KEY: ${{ secrets.ATTIC_KEY }}
  NIX_EVAL_ARGS: "--eval-store unix:///host/nix/var/nix/daemon-socket/socket?root=/host"

jobs:
  flake-build:
    runs-on: stop/${{ matrix.system }}
    container:
      options: "--volume /nix:/host/nix"

    strategy:
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux

    steps:
      - uses: actions/checkout@v4

      - run: flake-build --attic-use=true --nom=false --system ${{ matrix.system }}
