# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  river = {
    pname = "river";
    version = "9bbd34a0e31b6d429df2d39a59d8990a9585e186";
    src = fetchgit {
      url = "https://codeberg.org/river/river.git";
      rev = "9bbd34a0e31b6d429df2d39a59d8990a9585e186";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ZfKh1PJB+S2x7/6SWqgvleQjM50EZKfNKl/pOwVNZCY=";
    };
    date = "2024-04-19";
  };
}
