# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  lms = {
    pname = "lms";
    version = "8.3.1";
    src = dockerTools.pullImage {
      imageName = "docker.io/lmscommunity/logitechmediaserver";
      imageDigest = "sha256:cfc80537aea7b413508fb858713bbd4adb38664885543a907acd2ba42afa9ee4";
      sha256 = "sha256-weCf2yvGSQaWcIJGtmT7e1MLnesIXBqvLGP4jruO7wU=";
      finalImageTag = "8.3.1";
    };
  };
  nix-aarch64-linux = {
    pname = "nix-aarch64-linux";
    version = "2.19.2";
    src = dockerTools.pullImage {
      imageName = "docker.io/nixos/nix";
      imageDigest = "sha256:935cdafedba76f86c45d01f30f243474c958e1099029b292e5f2fbeac5f8805e";
      sha256 = "sha256-o+JhCIfBw2C5ThDDSlZMtAUsG57QYiLIXsx9Qn5oClU=";
      finalImageTag = "2.19.2";
      arch = "arm64";
    };
  };
  nix-x86_64-linux = {
    pname = "nix-x86_64-linux";
    version = "2.19.2";
    src = dockerTools.pullImage {
      imageName = "docker.io/nixos/nix";
      imageDigest = "sha256:935cdafedba76f86c45d01f30f243474c958e1099029b292e5f2fbeac5f8805e";
      sha256 = "sha256-6Bgwlsis6M7apkGj0HGAd12tPrRwEjSn9jdoiWsiUDM=";
      finalImageTag = "2.19.2";
      arch = "amd64";
    };
  };
}
