# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  river = {
    pname = "river";
    version = "e29d66f1deeb410c61e892e12e94e9971e645320";
    src = fetchgit {
      url = "https://codeberg.org/river/river.git";
      rev = "e29d66f1deeb410c61e892e12e94e9971e645320";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Eywj0OrYOqqsZmuFSnwCoCIQLOX+HUHhPcgM/aTb9Jg=";
    };
    date = "2024-05-02";
  };
}
